POST http://localhost:3002/recommended
Content-Type: application/json

{
    "ngoNum": null,
    "hq": null,
    "scope": null,
    "established": null,
    "members": null,
    "fundings": null,
    "languages": null,
    "description": "hello",
    "continents": null,
    "countries": null,
    "activities": null
}