POST http://localhost:3002/recommended
Content-Type: application/json

{
    "ngoNum": 5, 
    "hq": ["France", "Spain"], 
    "scope": ["International"], 
    "established": [1950, 2000], 
    "members": [10, 100], 
    "funding": ["Membership fees or dues", "Funds from Religious Institutions", "Fundraising campaigns"], 
    "languages": ["Spanish", "French", "Afrikaans", "Swahili"], 
    "description": "Sustainable development of economy in Africa to enforce women and children rights", 
    "continents": ["Africa"], 
    "countries": ["Kenya", "Tanzania", "Ivory Coast"],
    "activities": ["Business and Industry", "Culture", "Development", "Advocacy and outreach", "Capacity building"]
}